@startuml
'https://plantuml.com/class-diagram

class HoneyBee {
doYourJob() : String
fly() : String
}

class Drone {
doYourJob(): String
}

class Queen {
doYourJob(): String
}

class Worker {
doYourJob(): String
}

HoneyBee <|-- Worker
HoneyBee <|-- Queen
HoneyBee <|-- Drone

@enduml